---
title: "Curriculum Vitae"
editor: visual
css: styles.css
---
::: {style="font-size: 1.5em;"}
<u>***Education:***</u>\
:::
**PhD in Geosciences** [2025 - present]\
*Colorado State University, Fort Collins CO*\

**MS in Geosciences** [2023 - 2025],  <small> GPA: 4.0 </small>\
*Colorado State University, Fort Collins CO*\
  - <small>Master's Thesis: "Determining Primary Drivers of River Bead Functionality in Mountain Headwaters Streams"</small>\
  - <small>Activities and societies: GeoGSO Vice President ‘24-‘25, GSC Member, PROGRESS Mentor, GAAP Vice President ‘24-25</small>\

**BS in Geology (with Honors)** [2018 - 2022], <small> GPA: 3.7 </small>\
*Washington and Lee University, Lexington VA*\
  - <small>Honors Thesis: "The Removal of the Jordan's Point Dam: Examining Channel Restructure and Sediment Mobilization"</small>\
  - <small>Activities and societies: Women's Varsity Cross County, Women's Varsity Track & Field, InGeneral Magazine</small>\

**High School Diploma (with Distinguished Honors)** [2014 - 2018],  <small> GPA: 4.0 </small>\
*J.P. McCaskey High School, Lancaster PA*\
  - <small>Activities and societies: Varsity Cross Country, Varsity Track and Field, National Honor Society, Choir, Vidette Newspaper</small>\
  
::: {style="font-size: 1.5em;"}
<u>***Teaching:***</u>\
:::
**Academic Consultant** [May 2024]\
  - <small>Assisted in teaching Geology of Hawaii class for Washington & Lee University.</small>\

**Intro Geology** [Spring 2024]\
  - <small>Managed 4 lab sections with a total of 90 students.</small>\

**Hydrogeology** [Fall 2023]\
  - <small>Managed 2 lab sections with a total of 13 students.</small>\

::: {style="font-size: 1.5em;"}
<u>***Experience:***</u>\
:::
**GRA** [Spring 2024 - present]\
  - <small>Conducting MS & PhD research as a student in the CSU Fluvial Geomorphology Lab.</small>\

**GTA** [Fall 2023 - Spring 2024]\
  - <small>Led labs, graded assignments, and held office hours for Hydrogeology (Fall 2023) and Intro Geology (Spring 2024).</small>\

**Geologist 1** [Aug. 2022 - July 2023]\
  - <small>Conduced extensive fieldwork and helped write reports for US Government- and privately-funded environmental remediation projects</small>\
  - <small>Accumulated skills in sampling of water and soil, client communication, large-scale data management, and leadership</small>\

**Researcher** [Summer 2021]\
  - <small>Participated in a 2021 Advanced Research Project investigating milldam-induced legacy sedimentation and geomorphic signals and responses associated with their removal.</small>\
  - <small>Culminated in a first-author poster presented at GSA Connects 2021 and an Honors Thesis (completed in 2022).</small>\

**Geological Technician** [Summer 2020]\
  - <small>Conducted field sampling of water and soil for environmental remediation projects.</small>\
  - <small>Conducted extensive door-to-door well surveys to examine scope of contamination and communicate risk.</small>\

::: {style="font-size: 1.5em;"}
<u>***Honors:***</u>\
:::
**2022:** Honors in Geology, <small>Washington & Lee University</small>\
**2022:** Lena T. Stevens Award, <small>Washington & Lee Department of Geology</small>\
**2021:** Marcellus H. Stow Award, <small>Washington & Lee Department of Geology</small>\
**2020-2021:** President's List, <small>Washington & Lee University</small>\
**2019-2020:** President's List, <small>Washington & Lee University</small>\
**2019:** Departmental Award, <small>Washington & Lee Department of Geology</small>\

::: {style="font-size: 1.5em;"}
<u>***Scholarships:***</u>\
:::
**2025:** J.W. Powell Scholarship, <small>CSU Department of Geosciences</small>\
**2024:** Geological Society of America (GSA) Graduate Student Research Grant\
**2024:** Sustaining Colorado Watersheds Conference Scholarship\
**2024:** Class of 73 Scholars Award, <small>CSU Department of Geosciences</small>\
**2021:** Edgar W. Spencer '53 Geology Field Research Fund, <small>Washington & Lee Department of Geology</small>\

::: {style="font-size: 1.5em;"}
<u>***Fellowships:***</u>\
:::
**2024:** Marie Morisawa Graduate Fellowship, <small>CSU Department of Geosciences</small>\
**2021:** Keck Geology Consortium Fellowship\

::: {style="font-size: 1.5em;"}
<u>***Publications:***</u>\
:::
Wohl, E., Triantafillou, S., Thornton-Dunwoody, A., Mertz, C., **Larkin, K.**, Keenan, W., Griffin, S., Davis, D., and Blehm, L. Strategies for Assessing Post-Wildfire Geomorphic Resilience in Semiarid Rivers. \[Submitted to *River Research & Applications*, in review\]

Larkin, K. & Wohl, E. Determining Primary Drivers of River Bead Functionality in Mountain Headwaters Streams. \[Submitted to *Geomorphology*, in review\]

::: {style="font-size: 1.5em;"}
<u>***Presentations:***</u>\
:::
Wohl, E., **Larkin, K.**, and Triantafillou, S. Headwater Streams: What We Do and Don't Know. 2025. Invited talk presented at the American Geophysical Union Annual Meeting. 

Larkin, K. & Wohl, E. The Influence of Beaver on River Bead Functionality. 2025. Virtual presentation given to the Beaver Institute.\

Larkin, K. & Wohl, E. Determining Primary Drivers of River Bead Functionality in Mountain Headwaters Streams. 2025. Master's Thesis publicly presented at Colorado State University.\

Larkin, K. The Removal of the Jordan's Point Dam: Examining Channel Restructure and Sediment Mobilization. 2022. Honors Thesis publicly presented at Washington & Lee University.\

::: {style="font-size: 1.5em;"}
<u>***Posters:***</u>\
:::
Larkin, K. & Wohl, E. Determining Primary Drivers of River Bead Functionality in Mountain Headwaters Streams. Poster session presented at the American Geophysical Union Annual Meeting, December 12, 2024; Washington, DC.\

Larkin, K., Iosso, C., Harbor, D., Hinkle, M.A., and Lyon, E. Channel Morphology Change and Legacy Sediment Mobilization Following Dam Removal on the Maury River in Lexington, VA. Poster session presented at Geological Society of America Annual Scientific Meeting, October 12, 2021; Portland, OR.

Groff, M., Holicky, M., **Larkin, K.**, Pulido, M., Wilde, K., Hinkle, M.A., and Lyon, E. Characterizing Land Use History and Assessing Potential Geochemical Contaminants from Legacy Sediment and Impounded Water in Rockbridge County, VA. Poster session presented at Geological Society of America Annual Scientific Meeting, October 12, 2021; Portland, OR.

::: {style="font-size: 1.5em;"}
<u>***Professional Memberships:***</u>\
:::
  - AGU\
  - GSA\
  - AAG\

::: {style="font-size: 1.5em;"}
<u>***Skills:***</u>\
:::
  - Git/GitHub
  - R (coding language)
  - ArcGIS Pro
  - Microsoft Office 
:::

------------------------------------------------------------------------
